#!/usr/bin/env -S npx tsx
/**
 * Synthesizes a realistic forge home at a chosen size, for the load-verification harness
 * only (`docs/load-verify.md`, `scripts/load/run-benchmark.ts`). Never used by production
 * code and never pointed at a real `~/.forge` -- callers pass `--home` explicitly and this
 * script refuses to run without it.
 *
 * Row shapes are read straight off `src/forge/journal.ts` (ForgeEvent/Usage), `chain.ts`
 * (the chain.* hops), `registry.ts` (RegistryRecord), `supervisor.ts` (LaneRecord) and
 * `inbox.ts` (InboxEntry) rather than guessed, so a benchmark against this fixture
 * exercises the same fold, index and filter code a real fleet would.
 *
 * Every generated name is a placeholder (`alpha-N`, `AB-123`) on purpose: this file is
 * tracked, and `npm run check:agnostic` fails on a real company or product name in any
 * tracked file. Load only ever runs against a throwaway FORGE_HOME the caller builds
 * with this script, never against this repository's own working copy or `~/.forge`.
 */
import { mkdirSync, writeFileSync, createWriteStream, existsSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';

interface Options {
  home: string;
  runs: number;
  targetEvents: number | undefined;
  seed: number;
}

function parseArgs(argv: string[]): Options {
  const get = (flag: string): string | undefined => {
    const index = argv.indexOf(flag);
    return index >= 0 ? argv[index + 1] : undefined;
  };
  const home = get('--home');
  if (!home) {
    throw new Error('--home <dir> is required (a throwaway directory, never ~/.forge)');
  }
  return {
    home,
    runs: Number(get('--runs') ?? 100),
    targetEvents: get('--events') ? Number(get('--events')) : undefined,
    seed: Number(get('--seed') ?? 42),
  };
}

/** Deterministic PRNG so a size can be regenerated byte-for-byte for a repeat run. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const MODEL_IDS = ['claude-sonnet-5-20260101', 'claude-opus-5-20260101', 'claude-haiku-4-5-20251001'];
const CLASS_NAMES = [
  'triage', 'plan', 'master', 'implement', 'implement-hard', 'verify', 'audit-lens',
  'audit-judge', 'research', 'evaluate', 'sweep',
];
const TOOL_NAMES = ['Bash', 'Read', 'Edit', 'Write', 'Grep', 'Glob', 'WebFetch'];
const TICKET_LETTERS = ['AB', 'CD', 'EF', 'GH', 'JK'];

function ticketFor(i: number): string {
  const letters = TICKET_LETTERS[i % TICKET_LETTERS.length];
  return `${letters}-${100 + i}`;
}

/** ~40% of runs carry a ticket-shaped token in their own name, the way a real chain-
 *  launched run does (`ticketFor` in lanes.ts reads it back out of the name itself). */
function runName(i: number, rand: () => number): string {
  return rand() < 0.4 ? `${ticketFor(i)}_alpha-${i}` : `alpha-${i}`;
}

type Row = Record<string, unknown>;

/** One run's own event sequence, appended to `out` (the shared journal buffer) and
 *  returned as everything else (lane, registry, inbox, packet) needs to know about it. */
function genRun(input: {
  index: number;
  rand: () => number;
  toolCallsPerRun: number;
  now: number;
  seq: () => number;
  out: string[];
}): {
  run: string;
  ticket: string;
  className: string;
  model: string;
  state: 'running' | 'parked' | 'finished' | 'blocked' | 'handed-off';
  verdict?: string;
  askKey?: string;
  costUsd: number;
  context: number;
  packetId?: string;
} {
  const { index, rand, toolCallsPerRun, now, seq, out } = input;
  const run = runName(index, rand);
  const ticket = ticketFor(index);
  const className = CLASS_NAMES[Math.floor(rand() * CLASS_NAMES.length)]!;
  const model = MODEL_IDS[Math.floor(rand() * MODEL_IDS.length)]!;
  const startedAt = now - Math.floor(rand() * 6 * 60 * 60 * 1000);
  let at = startedAt;
  const push = (row: Row): void => {
    at += 1000 + Math.floor(rand() * 4000);
    out.push(JSON.stringify({
      id: randomUUID(), seq: seq(), at, version: 1, actor: 'runner', run, ticket, ...row,
    }));
  };

  push({ event: 'run.started', model, className });

  let costUsd = 0;
  let context = 0;
  const packetRoll = rand();
  const packetId = packetRoll < 0.2 ? `pkt-${index}` : undefined;
  if (packetId) {
    push({ event: 'intake.planned', actor: 'chain', packetId, ticket, repo: 'alpha/repo' });
    push({
      event: 'chain.provisioned', actor: 'chain', packetId,
      worktreePath: `worktrees/alpha--${index}`, branch: `feature/alpha-${index}`, base: 'main',
    });
    push({ event: 'chain.launched', actor: 'chain', packetId, runKey: run });
  }

  for (let call = 0; call < toolCallsPerRun; call += 1) {
    const tool = TOOL_NAMES[Math.floor(rand() * TOOL_NAMES.length)]!;
    push({ event: 'tool.start', tool });
    push({ event: 'tool.end', tool });
    if (call % 3 === 2) {
      const usage = {
        input: 2000 + Math.floor(rand() * 3000),
        cacheRead: 4000 + Math.floor(rand() * 20000),
        cacheCreation: Math.floor(rand() * 2000),
        output: 200 + Math.floor(rand() * 800),
      };
      context = usage.input + usage.cacheRead;
      const price = model.startsWith('claude-opus') ? { i: 15, cr: 1.5, cw: 18.75, o: 75 }
        : model.startsWith('claude-haiku') ? { i: 1, cr: 0.1, cw: 1.25, o: 5 }
          : { i: 3, cr: 0.3, cw: 3.75, o: 15 };
      costUsd += (usage.input * price.i + usage.cacheRead * price.cr
        + usage.cacheCreation * price.cw + usage.output * price.o) / 1e6;
      push({ event: 'turn.end', context, usage, model });
    }
  }

  const outcomeRoll = rand();
  if (outcomeRoll < 0.14) {
    push({ event: 'ask.raised', key: `ask-${index}`, question: 'proceed with alpha or beta?', options: ['alpha', 'beta'] });
    push({ event: 'run.parked', key: `ask-${index}`, verdict: 'parked' });
    if (packetId) push({ event: 'chain.blocked', packetId, hop: 'gate', reason: 'awaiting an answer' });
    return { run, ticket, className, model, state: 'parked', askKey: `ask-${index}`, costUsd, context, packetId };
  }
  if (outcomeRoll < 0.28) {
    // still running: no terminal row, a live registry row backs it.
    return { run, ticket, className, model, state: 'running', costUsd, context, packetId };
  }
  if (outcomeRoll < 0.34) {
    push({ event: 'run.blocked', reason: 'needs a decision on the wallet cap' });
    return { run, ticket, className, model, state: 'blocked', costUsd, context, packetId };
  }
  const verdict = outcomeRoll < 0.88 ? 'done' : outcomeRoll < 0.94 ? 'exhausted' : 'killed';
  push({ event: 'run.finished', verdict });
  if (packetId && verdict === 'done') {
    push({ event: 'chain.gated', packetId, verdict: 'pass' });
    push({ event: 'chain.merged', packetId, mergeSha: `${index.toString(16)}abc123` });
    push({ event: 'external.complete', kind: 'jira-transition', ticket });
  }
  return { run, ticket, className, model, state: 'finished', verdict, costUsd, context, packetId };
}

function laneRecordFor(gen: ReturnType<typeof genRun>, now: number): Row {
  const verdictMap: Record<string, string | null> = {
    running: null, parked: null, blocked: null,
    finished: gen.verdict ?? 'done', 'handed-off': null,
  };
  return {
    slug: gen.run, column: gen.run, owner: 'forge', session_id: randomUUID(),
    claude_pid: 10000 + Math.floor(Math.random() * 50000),
    started: now - 3_600_000, ended: gen.state === 'finished' ? now : null,
    verdict: verdictMap[gen.state] ?? null, position: null, note: null, woken: 0,
    model: gen.model, context: gen.context, cost_usd: Number(gen.costUsd.toFixed(6)),
    handoff: null, className: gen.className,
  };
}

async function main(): Promise<void> {
  const opts = parseArgs(process.argv.slice(2));
  if (existsSync(opts.home) && opts.home.length < 8) {
    throw new Error(`refusing to generate into a suspiciously short path: ${opts.home}`);
  }
  const dirs = {
    lanes: join(opts.home, 'lanes'), inbox: join(opts.home, 'inbox'),
    packets: join(opts.home, 'packets'), registry: join(opts.home, 'registry'),
    runs: join(opts.home, 'runs'),
  };
  for (const dir of Object.values(dirs)) mkdirSync(dir, { recursive: true });
  mkdirSync(opts.home, { recursive: true });

  const rand = mulberry32(opts.seed);
  const now = Date.now();
  const toolCallsPerRun = opts.targetEvents
    ? Math.max(1, Math.round((opts.targetEvents / opts.runs - 4) / 2))
    : 10;

  const journalPath = join(opts.home, 'fleet.jsonl');
  const stream = createWriteStream(journalPath, { flags: 'w' });
  let seqCounter = 0;
  const seq = (): number => { seqCounter += 1; return seqCounter; };
  let written = 0;
  const flushBatch = (lines: string[]): void => {
    if (!lines.length) return;
    stream.write(`${lines.join('\n')}\n`);
    written += lines.length;
    lines.length = 0;
  };

  const batch: string[] = [];
  for (let i = 0; i < opts.runs; i += 1) {
    const gen = genRun({ index: i, rand, toolCallsPerRun, now, seq, out: batch });

    writeFileSync(join(dirs.lanes, `${gen.run.replace(/[^A-Za-z0-9._-]/g, '_')}.json`), `${JSON.stringify(laneRecordFor(gen, now), null, 2)}\n`);

    if (gen.state === 'running') {
      // Deliberately no `sessionId`: `forge up`'s `reconcileRegistry` treats a dead pid
      // with no session id as unresumable and only reports + drops the row (order 9 --
      // spend needs a decision already made, and a fabricated sessionId here would let
      // reconcile try to resume a session that never existed, reaching a real engine).
      writeFileSync(join(dirs.registry, `${gen.run.replace(/[^A-Za-z0-9._-]/g, '_')}.json`), JSON.stringify({
        goal: gen.run, cwd: `worktrees/alpha--${i}`, briefPath: `goals/alpha-${i}.md`,
        pid: 10000 + i, startedAt: now - 60_000, model: gen.model,
      }, null, 2));
    }

    if (gen.askKey) {
      writeFileSync(join(dirs.inbox, `${gen.askKey}.json`), JSON.stringify({
        key: gen.askKey, question: 'proceed with alpha or beta?', options: ['alpha', 'beta'],
        kind: 'question', runs: [gen.run], goals: [gen.run], asked: 1, at: now - 30_000,
        disposition: 'park',
      }, null, 2));
    }

    if (gen.packetId) {
      writeFileSync(join(dirs.packets, `${gen.run.replace(/[^A-Za-z0-9._-]/g, '_')}.md`), `# ${gen.ticket}\n\nHandoff packet for ${gen.run}.\n`);
    }

    if (batch.length >= 5000) flushBatch(batch);
    if (i % 200 === 0) process.stdout.write(`\r${i}/${opts.runs} runs generated`);
  }
  flushBatch(batch);
  await new Promise<void>((resolve, reject) => {
    stream.end((err: unknown) => (err ? reject(err) : resolve()));
  });

  process.stdout.write(
    `\n${opts.runs} runs, ${written} journal events written to ${journalPath}\n`,
  );
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
