import { chromium } from 'playwright';
import { readFileSync } from 'node:fs';
const token = readFileSync(process.env.USERPROFILE + '/.forge/server-token', 'utf8').trim();
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1600, height: 1100 } });
const errs = [];
p.on('pageerror', (e) => errs.push('PAGE: ' + e.message.slice(0, 160)));
p.on('console', (m) => { if (m.type() === 'error') errs.push('CONSOLE: ' + m.text().slice(0, 160)); });
await p.addInitScript((t) => { localStorage.setItem('forge-token', t); }, token);
await p.goto('http://127.0.0.1:4120/', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(4000);
await p.click('[data-testid="nav-machine"]');
await p.waitForTimeout(6000);
const ids = await p.$$eval('[data-testid]', (els) => [...new Set(els.map((e) => e.getAttribute('data-testid')))].filter((x) => !x.startsWith('nav-')));
console.log('testids on the machine screen:', ids.join(' | ').slice(0, 400));
const body = await p.evaluate(() => document.body.innerText.replace(/\s+/g, ' ').slice(0, 500));
console.log('text:', JSON.stringify(body.slice(0, 400)));
console.log('errors:', errs.length ? errs.join(' || ') : 'none');
await p.screenshot({ path: 'C:/Users/aaron/AppData/Local/Temp/claude/machine2.png', fullPage: true });
await b.close();
